# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart.xci
# IP: The module: 'fifo_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: F:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart.xci
# IP: The module: 'fifo_uart' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: f:/workspace/project/prj_ax7103/prj_ax7103/prj_ax7103.srcs/sources_1/ip/fifo_uart/fifo_uart_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_uart'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
